FROM elixir:latest

ENV APP_HOME /graphql-demo
WORKDIR $APP_HOME

# Install base system dependencies
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      apt-utils \
      inotify-tools

# Install Node
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y nodejs

# Install Mix dependencies
RUN mix local.hex --force && \
    mix local.rebar --force

COPY . $APP_HOME